name: SimpleMaintenance
version: '@version@'
main: me.jonakls.spigotmaintenance.SimpleMaintenanceSpigot
author: Jonakls
commands:
  simplemaintenance:
    description: General command of plugin
    aliases:
      - sm
      - maintenance
      - swhitelist
