name: SimpleMaintenance
version: '${version}'
main: me.jonakls.bungeemaintenance.SimpleMaintenanceSpigot
author: Jonakls
commands:
  simplemaintenance:
    description: General command of plugin
    aliases:
      - sm
      - maintenance
      - swhitelist
