name: SimpleMaintenance
version: '${project.version}'
main: me.jonakls.spigot.SpigotPlugin
author: Jonakls
commands:
  simplemaintenance:
    description: General command of plugin
    aliases:
      - sm
      - maintenance
      - swhitelist
